In [5]:
import pandas as pd
!import plotly
!import plotly.express as px
import numpy as np
churn_data = pd.read_csv('data/churn.csv')
churn_data.head()

"import" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
"import" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

Столбцы таблицы:

RowNumber — номер строки таблицы (это лишняя информация, поэтому можете сразу от неё избавиться)
CustomerId — идентификатор клиента
Surname — фамилия клиента
CreditScore — кредитный рейтинг клиента (чем он выше, тем больше клиент брал кредитов и возвращал их)
Geography — страна клиента (банк международный)
Gender — пол клиента
Age — возраст клиента
Tenure — сколько лет клиент пользуется услугами банка
Balance — баланс на счетах клиента в банке
NumOfProducts — количество услуг банка, которые приобрёл клиент
HasCrCard — есть ли у клиента кредитная карта (1 — да, 0 — нет)
IsActiveMember — есть ли у клиента статус активного клиента банка (1 — да, 0 — нет)
EstimatedSalary — предполагаемая заработная плата клиента
Exited — статус лояльности (1 — ушедший клиент, 0 — лояльный клиент)

In [6]:
churn_data = churn_data.drop('RowNumber', axis=1)
display(churn_data)

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

9.1. Каково соотношение ушедших и лояльных клиентов? Покажите это на графике и дайте комментарий по соотношению.

In [7]:
churn_data['type_client'] = np.where(churn_data['Exited'] == 1, 'Ушедшие', 'Лояльные')
pie_chart = churn_data[['type_client','Exited']].copy()
pie_chart = churn_data.groupby(by='type_client', as_index=False)['Exited'].count()
type_client_sum = pie_chart['Exited'].sum()
pie_chart['type_client_per'] = round((pie_chart['Exited'] * 100) / type_client_sum)
fig = px.pie(pie_chart, 
             values="type_client_per", 
             names="type_client",
             width=700, height=700,
             color='type_client',
             color_discrete_map={"Лояльные": "lightgreen", "Ушедшие": "lightback"}
             )
fig.update_layout(title_text='Cоотношение ушедших и лояльных клиентов.', title_x=0.5)
fig.show()

<80% клиентов банка лояльны. Клиенты в подовляющем большинстве лояльны к банку. Банк осуществляет эффективную деятельность по работе с клиентами. Банк успешный и стабильный.>

9.2. Постройте график, показывающий распределение баланса пользователей, у которых на счету больше 2 500 долларов. Опишите распределение и сделайте выводы.

In [8]:
boxplot_chart = churn_data[(churn_data['Balance'] > 2500)] ['Balance'].copy()
fig = px.box(data_frame=boxplot_chart, x = "Balance")
fig.update_layout(title_text='Распределение по балансам клиентов с балансом больше 2 500 долларов.', title_x=0.5)
# fig.update_layout(set_ylabel='Клиенты (активные и выбывшие).')
# fig.set_title('Распределение по балансам клиентов с балансом > 2500')
# fig.set_ylabel('Клиенты (активные и выбывшие)')
fig.show()